<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h2>Aqui é o header</h2>
        
        <nav>
            <a href="home">Home</a>
            <a href="slim">Slim</a>
        </nav>
    </header>

    <?=$content?>

    <footer>Aqui é o footer</footer>
</body>
</html>